# Generated by Django 4.0.2 on 2022-02-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_billingaddress_order_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='countries',
        ),
    ]
